fix typo
design-pattern-ru/design-pattern-ru.github.io pull request #10
Opened 2018-02-08 10:52 UTC by dmnbars

Исправлена опечатка на странице о Мартине Фаулере

2018-02-08 18:59 UTC, samizdam requested changes

2018-02-08 18:59 UTC, samizdam commented on martin-fowler.html
> +            <p>На этом сайте использована информация, размещённая <noindex><a href="http://martinfowler.com/eaaCatalog/index.html">на сайте Маритина Фаулера</a></noindex> — переведённая и доработанна
Имя за одно исправьте, пожалуйста. 
Мартин, а не «Маритин»

2018-02-08 19:07 UTC, dmnbars commented on martin-fowler.html
> +            <p>На этом сайте использована информация, размещённая <noindex><a href="http://martinfowler.com/eaaCatalog/index.html">на сайте Маритина Фаулера</a></noindex> — переведённая и доработанна
поправил

2018-02-09 20:58 UTC, samizdam approved these changes

2018-02-10 23:04 UTC, samizdam commented
Похоже мэйнтейнера (a.k.a.  @coylone) надо пнуть в телеграмме, чтобы он увидел реквест. 
По крайней мере он написал так на главной проекта... 
Я телеграммом не пользуюсь.

2018-02-11 07:43 UTC, dmnbars commented
Это я сделал, сразу как создал реквест. Обещал глянуть.

2018-02-15 12:06 UTC, coyl commented
Спасибо!

2018-02-15 12:07 UTC, merged